// docroot/modules/contrib/canvas/modules/canvas_headless/examples/tanstack-start/src/components/image-display/index.tsx
interface CanvasImage {
  src: string
  alt: string
  width: number
  height: number
}

export default function ImageDisplay({ image }: { image: CanvasImage }) {
  return (
    <img
      className="h-auto w-full rounded-2xl md:col-span-2"
      src={image.src}
      alt={image.alt}
      width={image.width}
      height={image.height}
    />
  )
}

// docroot/modules/contrib/canvas/modules/canvas_headless/examples/nuxt/app/components/image-display/index.vue
<script setup lang="ts">
interface CanvasImage {
  src: string;
  alt: string;
  width: number;
  height: number;
}

defineProps<{
  image: CanvasImage;
}>();
</script>

<template>
  <img
    class="h-auto w-full rounded-2xl md:col-span-2"
    :src="image.src"
    :alt="image.alt"
    :width="image.width"
    :height="image.height"
  />
</template>
