// docroot/modules/contrib/canvas/modules/canvas_headless/examples/nuxt/app/components/action-link/index.vue
<script setup lang="ts">
defineProps<{
  label: string;
  href: string;
}>();
</script>

<template>
  <a
    class="inline-flex min-h-12 items-center justify-center self-start rounded-full bg-cyan-300 px-6 py-3 font-semibold text-slate-950 transition hover:bg-cyan-200 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-300"
    :href="href"
  >
    {{ label }}
  </a>
</template>

// docroot/modules/contrib/canvas/modules/canvas_headless/examples/tanstack-start/src/components/action-link/index.tsx
export default function ActionLink({
  label,
  href,
}: {
  label: string
  href: string
}) {
  return (
    <a
      className="inline-flex min-h-12 items-center justify-center self-start rounded-full bg-cyan-300 px-6 py-3 font-semibold text-slate-950 transition hover:bg-cyan-200 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-300"
      href={href}
    >
      {label}
    </a>
  )
}
